title: The Poet Coder
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: thepoetcoder@gmail.com
  facebook:
  flickr:
  github: ThePoetCoder
  instagram:
  linkedin:
  pinterest:
  reddit: /u/thepoetcoder
  rss: # just type anything here for a working RSS icon
  twitter: thepoetcoder
  stackoverflow: users/9885313/thepoetcoder
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
